
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Disable New Architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

target 'ecorismap' do
  $static_framework = []
  use_expo_modules!

  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  # Flags change depending on the env values.
  flags = get_default_flags()

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
  )

    # React Native Maps dependencies
    rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
    #pod 'Firebase/Analytics'

    ####
    #### https://github.com/react-native-maps/react-native-maps/issues/3597#issuecomment-1340367630
    ####
    
    $static_framework += [
      'react-native-gdalwarp',
      'react-native-maps',
      'react-native-google-maps',
      'Google-Maps-iOS-Utils',
      'GoogleMaps',
      'RNPermissions',
      'Permission-LocationWhenInUse',
      'Permission-Notifications',
      'react-native-paste-input',
      'vision-camera-code-scanner',
      'VisionCamera'
    ]
  
      # ****** THIS IS THE MAGIC ******
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
        installer.pod_targets.each do |pod|
            if $static_framework.include?(pod.name)
                def pod.build_type;
                Pod::BuildType.static_library # >= 1.9
            end
        end
    end
  end

   

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Workaround for Xcode 26: newer Apple Clang breaks consteval in fmt 11.0.2.
    fmt_base = File.join(installer.sandbox.root, 'fmt', 'include', 'fmt', 'base.h')
    if File.exist?(fmt_base)
      content = File.read(fmt_base)
      unless content.include?('Xcode 26 workaround')
        patched = content.gsub(
          /^(#elif defined\(__cpp_consteval\)\n#  define FMT_USE_CONSTEVAL) 1/,
          "// Xcode 26 workaround: disable consteval\n\\1 0"
        )
        if patched != content
          File.chmod(0644, fmt_base)
          File.write(fmt_base, patched)
        end
      end
    end

    # Workaround for Swift 6.3 async let crash in FirebaseFunctions 12.2.0
    # See: https://github.com/firebase/firebase-ios-sdk/pull/15991
    functions_context = File.join(installer.sandbox.root, 'FirebaseFunctions', 'FirebaseFunctions', 'Sources', 'Internal', 'FunctionsContext.swift')
    if File.exist?(functions_context)
      content = File.read(functions_context)
      if content.include?('async let authToken')
        patched = content.sub(
          /  func context\(options: HTTPSCallableOptions\?\) async throws -> FunctionsContext \{.*?^  \}/m,
          <<~'SWIFT'
  func context(options: HTTPSCallableOptions?) async throws -> FunctionsContext {
    // Patched: async let -> Task to work around Swift 6.3 regression (Xcode 26.4)
    // See: https://github.com/firebase/firebase-ios-sdk/pull/15991
    let authToken = Task { try await auth?.getToken(forcingRefresh: false) }
    let appCheckToken = Task { await getAppCheckToken(options: options) }
    let limitedUseAppCheckToken = Task { await getLimitedUseAppCheckToken(options: options) }

    return try await withTaskCancellationHandler {
      defer {
        authToken.cancel()
        appCheckToken.cancel()
        limitedUseAppCheckToken.cancel()
      }
      return try await FunctionsContext(
        authToken: authToken.value,
        fcmToken: messaging?.fcmToken,
        appCheckToken: appCheckToken.value,
        limitedUseAppCheckToken: limitedUseAppCheckToken.value
      )
    } onCancel: {
      authToken.cancel()
      appCheckToken.cancel()
      limitedUseAppCheckToken.cancel()
    }
  }
          SWIFT
        )
        if patched != content
          File.chmod(0644, functions_context)
          File.write(functions_context, patched)
          Pod::UI.puts "Patched FunctionsContext.swift: async let -> Task workaround"
        end
      end
    end

    installer.pods_project.targets.each do |target|
      if target.name == 'RNZipArchive'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
              file.settings['COMPILER_FLAGS'] = ''
          end
        end
      end
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
      end
    end
      
    bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
    def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
      framework_path = File.join(Dir.pwd, framework_relative_path)
      command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
      puts "Stripping bitcode: #{command}"
      system(command)
    end

    framework_paths = [
      "Pods/VSCCrypto/Carthage/iOS/VSCCommon.framework/VSCCommon",
      "Pods/VSCCrypto/Carthage/iOS/VSCFoundation.framework/VSCFoundation",
      "Pods/VSCCrypto/Carthage/iOS/VSCPythia.framework/VSCPythia",
    ]

    framework_paths.each do |framework_relative_path|
      strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
    end
  end
end
