default_platform(:ios)

platform :ios do
  desc "Build and upload app to App Store"
  lane :release do
    setup_ci

    # Apple APIキーの保存
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_content: Base64.decode64(ENV['APP_STORE_CONNECT_API_KEY_BASE64']),
      is_key_content_base64: false,
      in_house: false
    )

    match(
      type: "appstore",
      readonly: false,
      api_key: api_key
    )

    build_app(
      scheme: "ecorismap",
      workspace: "ecorismap.xcworkspace",
      export_method: "app-store",
      output_directory: "build",
      output_name: "ecorismap.ipa",
      export_options: {
        provisioningProfiles: {
          "jp.co.ecoris.ecorismap" => "match AppStore jp.co.ecoris.ecorismap"
        }
      },
      api_key: api_key
    )

    upload_to_app_store(
      ipa: "build/ecorismap.ipa",
      skip_metadata: true,
      skip_screenshots: true,
      api_key: api_key
    )
  end
end
