name: Android CI and Deploy
on: [push, workflow_dispatch]
jobs:
  build-and-deploy:
    name: Build and Deploy Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Install deps
        run: yarn install
      - name: Create local.properties
        run: |
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > android/local.properties
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON > android/app/google-services.json
      - name: Download and integrate react-native-gdalwarp
        run: |
          curl -L -o react-native-gdalwarp.zip https://github.com/tmizu23/build_gdal_android_ios/releases/download/v0.0.1/react-native-gdalwarp.zip
          unzip react-native-gdalwarp.zip
          mkdir -p modules
          cp -r react-native-gdalwarp modules/
      - name: Setup Android keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore
      - name: Get and increment version code
        run: |
          # Get the current highest version code from Google Play Console using git tags or commit count
          # Option 1: Use git commit count (always increasing)
          VERSION_FROM_COMMITS=$(git rev-list --count HEAD)
          
          # Option 2: Get from build.gradle as baseline
          VERSION_FROM_GRADLE=$(grep "versionCode" android/app/build.gradle | grep -o '[0-9]\+' | tail -1)
          
          # Use the higher value to ensure it's always increasing
          if [ $VERSION_FROM_COMMITS -gt $VERSION_FROM_GRADLE ]; then
            NEW_VERSION=$VERSION_FROM_COMMITS
          else
            # If gradle version is higher, use gradle version + 1
            NEW_VERSION=$((VERSION_FROM_GRADLE + 1))
          fi
          
          echo "Commit count: $VERSION_FROM_COMMITS"
          echo "Gradle version: $VERSION_FROM_GRADLE"
          echo "New version code: $NEW_VERSION"
          
          # Set as environment variable
          echo "VERSION_CODE=$NEW_VERSION" >> $GITHUB_ENV
          
          # Create whatsnew files with the build number
          mkdir -p whatsnew
          echo "Build $NEW_VERSION" > whatsnew/whatsnew-ja-JP
          echo "Build $NEW_VERSION" > whatsnew/whatsnew-en-US
      - name: Update AppConstants with build number
        run: |
          # Update VERSION in AppConstants.tsx to include build number
          sed -i "s/export const VERSION = 'Version \([^']*\)'/export const VERSION = 'Version \1 (Build $NEW_VERSION)'/" src/constants/AppConstants.tsx
          echo "Updated VERSION to include Build $NEW_VERSION"
      - name: Build Release
        env:
          STORE_FILE: release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: cd android && ./gradlew bundleRelease
      - name: Setup Google Play Config
        run: |
          echo '${{ secrets.PLAY_STORE_CONFIG_JSON }}' > play-store-config.json
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: play-store-config.json
          packageName: jp.co.ecoris.ecorismap
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          whatsNewDirectory: whatsnew
