name: iOS Build and Upload
on: [push, workflow_dispatch]
jobs:
  build-and-upload:
    name: Build and Upload to App Store
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Create Maps.plist
        run: |
          mkdir -p ios/ecorismap/Supporting
          cat << EOF > ios/ecorismap/Supporting/Maps.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>APIKey</key>
            <string>${{ secrets.MAPS_API_KEY }}</string>
          </dict>
          </plist>
          EOF

      - name: Create GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/ecorismap/GoogleService-Info.plist

      - name: Create ExportOptions.plist
        run: |
          echo '${{ secrets.EXPORT_OPTIONS }}' > ExportOptions.plist

      - name: Create Private Key
        run: |
          mkdir private_keys
          echo -n '${{ secrets.APPLE_API_KEY_BASE64 }}' | base64 --decode > ./private_keys/AuthKey_${{ secrets.APPLE_API_ISSUER_ID }}.p8

      - name: Download and integrate react-native-gdalwarp
        run: |
          curl -L -o react-native-gdalwarp.zip https://github.com/tmizu23/build_gdal_android_ios/releases/download/v0.0.1/react-native-gdalwarp.zip
          unzip react-native-gdalwarp.zip
          mkdir -p modules
          cp -r react-native-gdalwarp modules/

      - name: Install dependencies
        run: yarn install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Import Code Signing Certificates
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/${{ secrets.PROVISIONING_PROFILE_NAME }}

      - name: Archive Project
        run: |
          xcodebuild archive \
            -workspace ios/ecorismap.xcworkspace \
            -scheme ecorismap \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ecorismap.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ecorismap.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath app.ipa

      - name: Upload IPA to App Store Connect
        run: |
          xcrun altool --upload-app -f app.ipa/ecorismap.ipa \
                       -u ${{ secrets.APPLE_ID }} \
                       -p ${{ secrets.APP_SPECIFIC_PASSWORD }} \
                       --type ios
